=== Stephen-Cameron-Data-Services/isis-agri/fixture/src/main/java/au/com/scds/agric/fixture/xml/AgricSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://scds.com.au/acric/fixture/xml/generated"
	xmlns:tns="http://scds.com.au/acric/fixture/xml/generated"
	elementFormDefault="qualified">


	<complexType name="ProductLineFixture">
		<sequence>
			<element name="name" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="product-type" type="tns:ProductTypeFixture" minOccurs="1" maxOccurs="1">
			</element>
			<element name="batches" type="tns:BatchListFixture" minOccurs="0" maxOccurs="1"></element>
		</sequence>
	</complexType>


	<complexType name="ProductTypeFixture">
		<sequence>
			<element name="name" type="string" minOccurs="1" maxOccurs="1"></element>
		</sequence>
	</complexType>


    <complexType name="BatchListFixture">
    	<sequence>
    		<element name="batch" type="tns:BatchFixture" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="BatchFixture">
    	<sequence>
    		<element name="created-on" type="dateTime" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="created-by" type="tns:PersonFixture"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="scheduled-for" type="dateTime" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="completed-on" type="dateTime" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="completed-by" type="tns:PersonFixture" minOccurs="0" maxOccurs="1"></element>
    		<element name="formulation" type="tns:FormulationFixture"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="component" type="tns:BatchComponentFixture"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    		<element name="sample" type="tns:SampleFixture"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="FormulationFixture">
    	<sequence>
    		<element name="id" type="ID" minOccurs="1" maxOccurs="1"></element>
    		<element name="name" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="description" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="ingredient" type="tns:IngredientFixture" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="PersonFixture">
    	<sequence>
    		<element name="id" type="ID" minOccurs="1" maxOccurs="1"></element>
    		<element name="firstname" type="string" minOccurs="1" maxOccurs="1"></element>
    		<element name="lastname" type="string" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="SampleFixture">
    	<sequence>
    		<element name="id" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="batch" type="tns:BatchFixture" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="test" type="tns:TestFixture" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="BatchComponentFixture">
    	<sequence>
    		<element name="id" type="ID" minOccurs="1" maxOccurs="1"></element>
    		<element name="ingredient" type="tns:IngredientFixture" minOccurs="0" maxOccurs="1"></element>
    		<element name="supplier" type="tns:SupplierFixture"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="manufacturer" type="tns:ManufacturerFixture"
    			minOccurs="0" maxOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="Party">
    	<sequence>
    		<element name="name" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="SupplierFixture">
    	<complexContent>
    		<extension base="tns:Party">
    			<sequence>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>
    
    <complexType name="ManufacturerFixture">
    	<complexContent>
    		<extension base="tns:Party">
    			<sequence>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="ProductItem">
    	<sequence>
    		<element name="id" type="ID" minOccurs="1" maxOccurs="1"></element>
    		<element name="production-code" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="batch" type="tns:BatchFixture" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="product-line" type="tns:ProductLineFixture" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="OrderLine">
    	<sequence>
    		<element name="id" type="ID"></element>
    		<element name="product-line"
    			type="tns:ProductLineFixture">
    		</element>
    		<element name="quantity" type="int"></element>
    	</sequence>
    </complexType>

    <complexType name="ScheduledOrderLineFixture">
    	<complexContent>
    		<extension base="tns:NewOrderLineFixture">
    			<sequence>
    				<element name="scheduled-on" type="dateTime"></element>
    				<element name="scheduled-by"
    					type="tns:PersonFixture">
    				</element>
    				<element name="scheduled-batch" type="string"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="CompletedOrderLineFixture">
    	<complexContent>
    		<extension base="tns:ScheduledOrderLineFixture">
    			<sequence>
    				<element name="completed" type="dateTime"></element>
    				<element name="completed-by" type="tns:PersonFixture"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="OrderFixture">
    	<sequence>
    		<element name="id" type="ID" minOccurs="1" maxOccurs="1"></element>
    		<element name="client" type="tns:ClientFixture"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="taken" type="dateTime" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="taken-by" type="tns:PersonFixture"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="order-line"
    			type="tns:NewOrderLineFixture" minOccurs="1"
    			maxOccurs="unbounded">
    		</element>
    		<element name="scheduled-order-line"
    			type="tns:ScheduledOrderLineFixture" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="completed-order-line"
    			type="tns:CompletedOrderLineFixture" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="delivery" type="tns:DeliveryFixture" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="NewOrderLineFixture">
    	<complexContent>
    		<extension base="tns:OrderLine">
    			<sequence>
    				<element name="added-on" type="dateTime"></element>
                    <element name="added-by" type="tns:PersonFixture" minOccurs="1" maxOccurs="1"></element>
                </sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="ClientFixture">
    	<complexContent>
    		<extension base="tns:Party">
    			<sequence>
    				<element name="order" type="tns:OrderFixture" minOccurs="0" maxOccurs="unbounded"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="DeliveryFixture">
    	<sequence>
    		<element name="delivery-date" type="dateTime" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="TestFixture">
    	<sequence>
    		<element name="name" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <element name="orders" type="tns:OrdersFixture"></element>

    <complexType name="OrdersFixture">
    	<sequence>
    		<element name="order" type="tns:OrderFixture" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>


    <element name="batches" type="tns:BatchesFixture"></element>

    <complexType name="BatchesFixture">
    	<sequence>
    		<element name="batch" type="tns:BatchFixture" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>


    <complexType name="IngredientFixture">
    	<sequence>
    		<element name="name" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="quantity" type="double" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="unit" type="string" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="TestSuiteFixture">
    	<sequence>
    		<choice minOccurs="1" maxOccurs="unbounded">
    			<element name="test" type="tns:TestFixture" minOccurs="0" maxOccurs="unbounded"></element>
    			<element name="test-group" type="tns:TestGroupFixture" minOccurs="0" maxOccurs="unbounded"></element>
    		</choice>
    	</sequence>
    </complexType>

    <complexType name="TestGroupFixture">
    	<sequence>
    		<element name="test" type="tns:TestFixture" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="ResultFixture">
    	<sequence>
    		<element name="name" type="string" minOccurs="1"></element>
    		<element name="result" type="double" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>
</schema>

=== Stephen-Cameron-Data-Services/isis-agri/fixture/src/main/resources/au/com/scds/agric/fixture/dom/batches.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:batches xmlns:tns="http://scds.com.au/acric/fixture/xml/generated"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://scds.com.au/acric/fixture/xml/generated AgricSchema.xsd ">
	<tns:batch>
		<tns:created-on>2016-07-20T10:00:00</tns:created-on>
		<tns:created-by>
			<tns:id>1</tns:id>
			<tns:firstname>Deborah</tns:firstname>
			<tns:lastname>White</tns:lastname>
		</tns:created-by>
		<tns:scheduled-for>2016-07-25T12:00:00</tns:scheduled-for>
		<tns:completed-on>2016-07-26T09:00:00</tns:completed-on>
		<tns:completed-by>
			<tns:id>1</tns:id>
			<tns:firstname>John</tns:firstname>
			<tns:lastname>Frost</tns:lastname>
		</tns:completed-by>
		<tns:formulation>
			<tns:id>1</tns:id>
			<tns:name>Double Cream Brie 2</tns:name>
			<tns:description>An improvement on the last formulation.</tns:description>
			<tns:ingredient>
				<tns:name>Full Cream Milk</tns:name>
				<tns:quantity>1000</tns:quantity>
				<tns:unit>litres</tns:unit>
			</tns:ingredient>
			<tns:ingredient>
				<tns:name>Cream</tns:name>
				<tns:quantity>100</tns:quantity>
				<tns:unit>litres</tns:unit>
			</tns:ingredient>
			<tns:ingredient>
				<tns:name>Rennet</tns:name>
				<tns:quantity>100</tns:quantity>
				<tns:unit>grams</tns:unit>
			</tns:ingredient>
			<tns:ingredient>
				<tns:name>Salt</tns:name>
				<tns:quantity>10</tns:quantity>
				<tns:unit>kilograms</tns:unit>
			</tns:ingredient>
			<tns:ingredient>
				<tns:name>Penicillium camemberti culture</tns:name>
				<tns:quantity>100</tns:quantity>
				<tns:unit>grams</tns:unit>
			</tns:ingredient>
		</tns:formulation>
		<tns:component>
			<tns:id>1</tns:id>
			<tns:ingredient>
				<tns:name>Full Cream Milk</tns:name>
			</tns:ingredient>
			<tns:supplier>
				<tns:name>Van Diemen's Land Company</tns:name>
			</tns:supplier>
		</tns:component>
		<tns:component>
			<tns:id>1</tns:id>
			<tns:ingredient>
				<tns:name>Cream</tns:name>
			</tns:ingredient>
			<tns:supplier>
				<tns:name>Van Diemen's Land Company</tns:name>
			</tns:supplier>
		</tns:component>
		<tns:sample>
			<tns:id>1</tns:id>
		</tns:sample>
	</tns:batch>
</tns:batches>

=== Stephen-Cameron-Data-Services/isis-agri/fixture/src/main/resources/au/com/scds/agric/fixture/dom/orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:orders xmlns:tns="http://scds.com.au/acric/fixture/xml/generated"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://scds.com.au/acric/fixture/xml/generated AgricSchema.xsd ">
	<tns:order>
		<tns:id>1</tns:id>
		<tns:client>
			<tns:name>Woolworths</tns:name>
		</tns:client>
		<tns:taken>2016-06-22T12:00:00</tns:taken>
		<tns:taken-by>
			<tns:id>1</tns:id>
			<tns:firstname>Sam</tns:firstname>
			<tns:lastname>Smith</tns:lastname>
		</tns:taken-by>
		<tns:order-line>
			<tns:id>1</tns:id>
			<tns:product-line>
				<tns:name>Whole Chicken</tns:name>
				<tns:product-type>
					<tns:name>Chicken Meat</tns:name>
				</tns:product-type>
			</tns:product-line>
			<tns:quantity>100</tns:quantity>
			<tns:added-on>2016-06-23T12:00:00</tns:added-on>
			<tns:added-by>
				<tns:id>2</tns:id>
				<tns:firstname>John</tns:firstname>
				<tns:lastname>Brown</tns:lastname>
			</tns:added-by>
		</tns:order-line>
	</tns:order>
	<tns:order>
		<tns:id>1</tns:id>
		<tns:client>
			<tns:name>IGA</tns:name>
		</tns:client>
		<tns:taken>2016-06-22T12:00:00</tns:taken>
		<tns:taken-by>
			<tns:id>1</tns:id>
			<tns:firstname>Sam</tns:firstname>
			<tns:lastname>Smith</tns:lastname>
		</tns:taken-by>
		<tns:order-line>
			<tns:id>1</tns:id>
			<tns:product-line>
				<tns:name>Double Cream Brie</tns:name>
				<tns:product-type>
					<tns:name>Cheese</tns:name>
				</tns:product-type>
			</tns:product-line>
			<tns:quantity>100</tns:quantity>
			<tns:added-on>2016-06-23T12:00:00</tns:added-on>
			<tns:added-by>
				<tns:id>2</tns:id>
				<tns:firstname>Trudy</tns:firstname>
				<tns:lastname>Clark</tns:lastname>
			</tns:added-by>
		</tns:order-line>
	</tns:order>
	<tns:order>
		<tns:id>1</tns:id>
		<tns:client>
			<tns:name>Salamanca Fresh</tns:name>
		</tns:client>
		<tns:taken>2016-06-22T12:00:00</tns:taken>
		<tns:taken-by>
			<tns:id>1</tns:id>
			<tns:firstname>Sam</tns:firstname>
			<tns:lastname>Smith</tns:lastname>
		</tns:taken-by>
		<tns:order-line>
			<tns:id>1</tns:id>
			<tns:product-line>
				<tns:name>Full Cream Milk</tns:name>
				<tns:product-type>
					<tns:name>Milk</tns:name>
				</tns:product-type>
			</tns:product-line>
			<tns:quantity>100</tns:quantity>
			<tns:added-on>2016-06-23T12:00:00</tns:added-on>
			<tns:added-by>
				<tns:id>2</tns:id>
				<tns:firstname>Mary</tns:firstname>
				<tns:lastname>Green</tns:lastname>
			</tns:added-by>
		</tns:order-line>
	</tns:order>
</tns:orders>
